spring:
  datasource:
    username: root
    password: chmaini3344
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  mail:
    host: smtp.163.com
    username: ChmaiLwj@163.com
    password: ICRRGMDKXCMHNNKS